# Generated by Django 2.0.5 on 2018-09-08 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariorang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcari',
            name='gender',
            field=models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], default='gender', max_length=10),
        ),
        migrations.AddField(
            model_name='postcari',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+62'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='postcari',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
