# Generated by Django 2.0.5 on 2018-09-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cariorang', '0002_auto_20180908_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Details',
        ),
    ]
