# Generated by Django 2.0.5 on 2018-09-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cariorang', '0003_auto_20180911_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cariorang.PostCari')),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
