# Generated by Django 2.0.5 on 2018-09-11 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cariorang', '0004_auto_20180911_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='message',
            field=models.TextField(default='message', max_length=5000),
        ),
        migrations.AddField(
            model_name='detail',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detail',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
