# Generated by Django 2.0.5 on 2018-09-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariorang', '0006_auto_20180911_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='message',
            field=models.TextField(default='mantan', max_length=5000),
        ),
    ]
