# Generated by Django 2.0.5 on 2018-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariorang', '0010_auto_20180911_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcari',
            name='approved_post',
            field=models.BooleanField(default=False),
        ),
    ]
