# Generated by Django 2.0.5 on 2018-09-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariorang', '0013_postcari_message_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcari',
            name='message_admin',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
