# Generated by Django 2.0.5 on 2018-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariorang', '0014_auto_20180917_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcari',
            name='ketemu',
            field=models.BooleanField(default=False),
        ),
    ]
