# Generated by Django 2.0.5 on 2018-10-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariorang', '0015_postcari_ketemu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='message',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
