# Generated by Django 2.0.5 on 2019-01-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariorang', '0017_postcari_ciri'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcari',
            name='titik_terakhir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
