# Generated by Django 2.0.5 on 2018-10-13 03:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('umur', models.PositiveIntegerField(blank=True)),
                ('tinggi', models.PositiveIntegerField(blank=True, null=True)),
                ('berat', models.PositiveIntegerField(blank=True, null=True)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='dpo/')),
                ('ciri', models.TextField(max_length=5000)),
                ('kelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], default='kelamin', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+62'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('approved_post', models.BooleanField(default=False)),
                ('message_admin', models.TextField(blank=True, default='', max_length=1000)),
                ('ketemu', models.BooleanField(default=False)),
                ('pasal', models.CharField(blank=True, max_length=20, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caridpo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
