# Generated by Django 2.0.5 on 2018-10-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdpo',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
