# Generated by Django 2.0.5 on 2018-10-14 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpo', '0003_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='DetailDPO',
        ),
    ]
